### POST Create a new Product
POST http://localhost:4000/products
Content-Type: application/json

{
  "title": "",
  "description": "Apple minimal white mouse ",
  "price": 399.99,
  "imageUrl": "https://example.com/img/apple-mouse.jpg"
}

###