### POST request to create client
POST http://localhost:4000/clients
Content-Type: application/json

{
    "name": "Jude Smith",
    "email": "smith@gmail.com",
    "bio": "Open-source lover and dev"
}

###