### POST request to create client
POST http://localhost:4000/clients
Content-Type: application/json

{
    "name": "Lucas Bobby kafka",
    "email": "lucaskafka@gmail.com",
    "bio": "UI lover and kafka dev"
}

###